import type { Database } from '@/types/database'

type ArtistRow = Database['public']['Tables']['artists']['Row']
type StyleRow = Database['public']['Tables']['styles']['Row']
type PortfolioItemRow = Database['public']['Tables']['portfolio_items']['Row']
type ArtistStyleRow = Database['public']['Tables']['artist_styles']['Row']

export const mockStyles: StyleRow[] = [
  { id: 1, slug: 'realism', name: '寫實', icon: '🎨' },
  { id: 2, slug: 'geometric', name: '幾何', icon: '📐' },
  { id: 3, slug: 'japanese-traditional', name: '日式傳統', icon: '🏯' },
  { id: 4, slug: 'american-traditional', name: '美式傳統', icon: '🦅' },
  { id: 5, slug: 'neo-traditional', name: '新傳統', icon: '🌹' },
  { id: 6, slug: 'watercolor', name: '水彩', icon: '💧' },
  { id: 7, slug: 'fine-line', name: '極簡線條', icon: '✏️' },
  { id: 8, slug: 'blackwork', name: '暗黑', icon: '🖤' },
  { id: 9, slug: 'floral', name: '花卉', icon: '🌸' },
  { id: 10, slug: 'lettering', name: '字體', icon: '✍️' },
  { id: 11, slug: 'dotwork', name: '點描', icon: '⚫' },
  { id: 12, slug: 'tribal', name: '部落圖騰', icon: '🔱' },
  { id: 13, slug: 'illustrative', name: '插畫', icon: '🖊️' },
  { id: 14, slug: 'anime', name: '漫畫/動漫', icon: '🎌' },
  { id: 15, slug: 'portrait', name: '肖像', icon: '👤' },
  { id: 16, slug: 'micro', name: '微刺青', icon: '🔍' },
  { id: 17, slug: 'coverup', name: '遮蓋/改圖', icon: '🔄' },
  { id: 18, slug: 'other', name: '其他', icon: '➕' },
]

const BODY_PARTS = ['手臂', '腿部', '背部', '胸部', '肩膀', '手腕', '腳踝', '手指'] as const
const SIZES = ['5x5', '8x8', '10x8', '12x10', '15x10', '15x15', '20x15', '20x20', '25x15', '30x20'] as const

function createPortfolioItems(
  artistId: string,
  styleIds: number[],
  count: number,
  seedPrefix: string,
): PortfolioItemRow[] {
  return Array.from({ length: count }, (_, i) => ({
    id: `${artistId}-portfolio-${i + 1}`,
    artist_id: artistId,
    image_url: `https://picsum.photos/seed/${seedPrefix}-${i + 1}/800/800`,
    thumbnail_url: `https://picsum.photos/seed/${seedPrefix}-${i + 1}/400/400`,
    title: null,
    description: null,
    body_part: BODY_PARTS[i % BODY_PARTS.length],
    size_cm: SIZES[i % SIZES.length],
    style_id: styleIds[i % styleIds.length],
    healed_image_url: null,
    sort_order: i + 1,
    created_at: '2025-01-15T10:00:00Z',
  }))
}

interface MockArtistData {
  artist: ArtistRow
  styleIds: number[]
  portfolioCount: number
  seedPrefix: string
}

const artistsData: MockArtistData[] = [
  {
    artist: {
      id: 'artist-001',
      slug: 'inkmaster-alex',
      display_name: 'Alex Chen 阿克',
      bio: '專注寫實風格超過 8 年，擅長黑灰寫實與彩色肖像。每一件作品都是獨一無二的藝術品。',
      avatar_url: 'https://picsum.photos/seed/alex-avatar/200/200',
      ig_handle: '@inkmaster_alex',
      line_user_id: null,
      city: '台北市',
      district: '大安區',
      address: null,
      lat: 25.0264,
      lng: 121.5436,
      price_min: 5000,
      price_max: 25000,
      pricing_note: '依圖案大小與複雜度報價',
      deposit_amount: 2000,
      booking_notice: '請提前兩週預約',
      status: 'active',
      is_claimed: true,
      featured: true,
      created_at: '2024-06-01T08:00:00Z',
      updated_at: '2025-01-10T12:00:00Z',
    },
    styleIds: [1, 15, 8],
    portfolioCount: 8,
    seedPrefix: 'alex',
  },
  {
    artist: {
      id: 'artist-002',
      slug: 'darkline-studio',
      display_name: 'DarkLine 暗線刺青',
      bio: '暗黑風格與幾何圖騰的完美結合。我們相信刺青是身體與靈魂的對話。',
      avatar_url: 'https://picsum.photos/seed/darkline-avatar/200/200',
      ig_handle: '@darkline_studio',
      line_user_id: null,
      city: '台北市',
      district: '中山區',
      address: null,
      lat: 25.0527,
      lng: 121.5207,
      price_min: 3000,
      price_max: 18000,
      pricing_note: '小圖 $3000 起，大圖面議',
      deposit_amount: 1500,
      booking_notice: '週一公休，線上預約制',
      status: 'active',
      is_claimed: true,
      featured: false,
      created_at: '2024-07-15T08:00:00Z',
      updated_at: '2025-01-12T12:00:00Z',
    },
    styleIds: [8, 2, 11],
    portfolioCount: 6,
    seedPrefix: 'darkline',
  },
  {
    artist: {
      id: 'artist-003',
      slug: 'sakura-ink',
      display_name: '小櫻 Sakura',
      bio: '日式傳統與花卉刺青專家。從浮世繪到現代花卉，用色彩說故事。',
      avatar_url: 'https://picsum.photos/seed/sakura-avatar/200/200',
      ig_handle: '@sakura_ink_tw',
      line_user_id: null,
      city: '新北市',
      district: '板橋區',
      address: null,
      lat: 25.0146,
      lng: 121.4627,
      price_min: 4000,
      price_max: 20000,
      pricing_note: '花卉小圖 $4000 起',
      deposit_amount: 2000,
      booking_notice: '預約請私訊 IG',
      status: 'active',
      is_claimed: true,
      featured: true,
      created_at: '2024-05-20T08:00:00Z',
      updated_at: '2025-01-08T12:00:00Z',
    },
    styleIds: [3, 9, 6],
    portfolioCount: 7,
    seedPrefix: 'sakura',
  },
  {
    artist: {
      id: 'artist-004',
      slug: 'tiny-tattoo-lin',
      display_name: 'Lin 小林',
      bio: '微刺青與極簡線條設計師。小而精緻，適合第一次刺青的你。',
      avatar_url: 'https://picsum.photos/seed/lin-avatar/200/200',
      ig_handle: '@tiny_tattoo_lin',
      line_user_id: null,
      city: '新北市',
      district: '永和區',
      address: null,
      lat: 25.0096,
      lng: 121.5138,
      price_min: 2000,
      price_max: 8000,
      pricing_note: '微刺青 $2000 起，手指刺青 $1500',
      deposit_amount: 1000,
      booking_notice: '當日可預約（視空檔）',
      status: 'active',
      is_claimed: true,
      featured: false,
      created_at: '2024-08-01T08:00:00Z',
      updated_at: '2025-01-15T12:00:00Z',
    },
    styleIds: [16, 7, 10],
    portfolioCount: 6,
    seedPrefix: 'lin',
  },
  {
    artist: {
      id: 'artist-005',
      slug: 'kai-traditional',
      display_name: 'KAI 凱',
      bio: '美式傳統老派風格。粗線條、飽和色彩、經典圖案。Old school is not dead.',
      avatar_url: 'https://picsum.photos/seed/kai-avatar/200/200',
      ig_handle: '@kai_oldschool',
      line_user_id: null,
      city: '台中市',
      district: '西區',
      address: null,
      lat: 24.1466,
      lng: 120.6740,
      price_min: 3500,
      price_max: 15000,
      pricing_note: '經典圖案 $3500 起，客製化另計',
      deposit_amount: 1500,
      booking_notice: '僅接受預約制',
      status: 'active',
      is_claimed: true,
      featured: false,
      created_at: '2024-09-01T08:00:00Z',
      updated_at: '2025-01-05T12:00:00Z',
    },
    styleIds: [4, 5, 13],
    portfolioCount: 5,
    seedPrefix: 'kai',
  },
  {
    artist: {
      id: 'artist-006',
      slug: 'miya-watercolor',
      display_name: 'Miya 米亞',
      bio: '水彩風格刺青藝術家。將水彩畫的溫柔暈染帶入刺青，每一筆都像在皮膚上作畫。',
      avatar_url: 'https://picsum.photos/seed/miya-avatar/200/200',
      ig_handle: '@miya_watercolor_ink',
      line_user_id: null,
      city: '台中市',
      district: '北區',
      address: null,
      lat: 24.1574,
      lng: 120.6833,
      price_min: 4500,
      price_max: 22000,
      pricing_note: '水彩風作品 $4500 起',
      deposit_amount: 2000,
      booking_notice: '請提前一個月預約',
      status: 'active',
      is_claimed: true,
      featured: true,
      created_at: '2024-04-10T08:00:00Z',
      updated_at: '2025-01-11T12:00:00Z',
    },
    styleIds: [6, 9, 13, 7],
    portfolioCount: 8,
    seedPrefix: 'miya',
  },
  {
    artist: {
      id: 'artist-007',
      slug: 'shadow-ink-kh',
      display_name: '阿影 Shadow',
      bio: '高雄在地刺青師，擅長暗黑與點描風格。用黑色詮釋你內心的故事。',
      avatar_url: 'https://picsum.photos/seed/shadow-avatar/200/200',
      ig_handle: '@shadow_ink_kh',
      line_user_id: null,
      city: '高雄市',
      district: '前鎮區',
      address: null,
      lat: 22.6127,
      lng: 120.3111,
      price_min: 3000,
      price_max: 16000,
      pricing_note: '暗黑風小圖 $3000 起',
      deposit_amount: 1500,
      booking_notice: '週二至週六營業',
      status: 'active',
      is_claimed: true,
      featured: false,
      created_at: '2024-10-01T08:00:00Z',
      updated_at: '2025-01-14T12:00:00Z',
    },
    styleIds: [8, 11, 12],
    portfolioCount: 5,
    seedPrefix: 'shadow',
  },
  {
    artist: {
      id: 'artist-008',
      slug: 'neko-anime-ink',
      display_name: 'Neko 貓貓',
      bio: '動漫與插畫風格專門店。從你最愛的角色到原創設計，讓二次元活在你的皮膚上。',
      avatar_url: 'https://picsum.photos/seed/neko-avatar/200/200',
      ig_handle: '@neko_anime_ink',
      line_user_id: null,
      city: '高雄市',
      district: '新興區',
      address: null,
      lat: 22.6291,
      lng: 120.3044,
      price_min: 3000,
      price_max: 12000,
      pricing_note: '動漫角色 $3000 起，彩色加 $1000',
      deposit_amount: 1000,
      booking_notice: '歡迎帶參考圖來討論',
      status: 'active',
      is_claimed: true,
      featured: false,
      created_at: '2024-11-01T08:00:00Z',
      updated_at: '2025-01-13T12:00:00Z',
    },
    styleIds: [14, 13, 7],
    portfolioCount: 6,
    seedPrefix: 'neko',
  },
  {
    artist: {
      id: 'artist-009',
      slug: 'iron-brush-wang',
      display_name: '王鐵筆 Iron Brush',
      bio: '書法字體刺青大師。結合東方書法藝術與現代刺青技術，讓文字成為你的護身符。',
      avatar_url: 'https://picsum.photos/seed/ironbrush-avatar/200/200',
      ig_handle: '@iron_brush_wang',
      line_user_id: null,
      city: '桃園市',
      district: '中壢區',
      address: null,
      lat: 24.9577,
      lng: 121.2257,
      price_min: 2500,
      price_max: 10000,
      pricing_note: '單字 $2500 起，句子依長度報價',
      deposit_amount: 1000,
      booking_notice: '請先傳想刺的文字內容',
      status: 'active',
      is_claimed: true,
      featured: false,
      created_at: '2024-12-01T08:00:00Z',
      updated_at: '2025-01-09T12:00:00Z',
    },
    styleIds: [10, 7, 16],
    portfolioCount: 4,
    seedPrefix: 'ironbrush',
  },
  {
    artist: {
      id: 'artist-010',
      slug: 'jade-coverup',
      display_name: 'Jade 小玉',
      bio: '遮蓋與改圖專家。不滿意舊刺青？讓我幫你重新設計，給它第二次生命。',
      avatar_url: 'https://picsum.photos/seed/jade-avatar/200/200',
      ig_handle: '@jade_coverup_tw',
      line_user_id: null,
      city: '桃園市',
      district: '桃園區',
      address: null,
      lat: 24.9935,
      lng: 121.3010,
      price_min: 5000,
      price_max: 30000,
      pricing_note: '遮蓋圖 $5000 起，需先看原圖評估',
      deposit_amount: 3000,
      booking_notice: '請先傳舊刺青照片評估',
      status: 'active',
      is_claimed: true,
      featured: false,
      created_at: '2024-03-15T08:00:00Z',
      updated_at: '2025-01-07T12:00:00Z',
    },
    styleIds: [17, 1, 5, 9],
    portfolioCount: 6,
    seedPrefix: 'jade',
  },
]

function getStylesForArtist(styleIds: number[]): StyleRow[] {
  return styleIds
    .map((id) => mockStyles.find((s) => s.id === id))
    .filter((s): s is StyleRow => s !== undefined)
}

export const mockArtistStyles: ArtistStyleRow[] = artistsData.flatMap(
  ({ artist, styleIds }) =>
    styleIds.map((styleId) => ({
      artist_id: artist.id,
      style_id: styleId,
    })),
)

export const mockArtists: (ArtistRow & {
  styles: StyleRow[]
  portfolio_items: PortfolioItemRow[]
})[] = artistsData.map(({ artist, styleIds, portfolioCount, seedPrefix }) => ({
  ...artist,
  styles: getStylesForArtist(styleIds),
  portfolio_items: createPortfolioItems(artist.id, styleIds, portfolioCount, seedPrefix),
}))

export const mockPortfolioItems: PortfolioItemRow[] = mockArtists.flatMap(
  (a) => a.portfolio_items,
)
