#!/usr/bin/env bash

set -euo pipefail

V2_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
V2_RUNTIME_DIR="${INKHUNT_V2_RUNTIME_DIR:-${V2_ROOT_DIR}/.local/v2-supabase-runtime}"
V2_PROJECT_ID="inkhunt-v2"
V2_API_URL="http://127.0.0.1:56321"
V2_DB_PORT="56322"
V2_DOCKER_CONFIG_DIR="${V2_RUNTIME_DIR}/docker-anonymous"

# Docker Desktop's credential helper can hang even for public registries on
# this machine. The v2 stack only pulls public Supabase images, so give these
# commands an isolated, credential-free Docker config without changing the
# user's global Docker configuration.
mkdir -p "${V2_DOCKER_CONFIG_DIR}"
export DOCKER_CONFIG="${V2_DOCKER_CONFIG_DIR}"

v2_prepare_runtime() {
  mkdir -p "${V2_RUNTIME_DIR}"
  rsync -a --delete --exclude '.temp' "${V2_ROOT_DIR}/supabase/" "${V2_RUNTIME_DIR}/supabase/"

  local config="${V2_RUNTIME_DIR}/supabase/config.toml"
  perl -0pi -e '
    s/project_id = "inkhunt"/project_id = "inkhunt-v2"/g;
    s/54320/56320/g;
    s/54321/56321/g;
    s/54322/56322/g;
    s/54323/56323/g;
    s/54324/56324/g;
    s/54327/56327/g;
    s/54329/56329/g;
    s/inspector_port = 8083/inspector_port = 56383/g;
    s#additional_redirect_urls = \["https://127\.0\.0\.1:3000"\]#additional_redirect_urls = ["http://127.0.0.1:3000", "http://127.0.0.1:3200"]#g;
    s#site_url = "http://127\.0\.0\.1:3000"#site_url = "http://127.0.0.1:3200"#g;
  ' "${config}"
}

v2_status_json() {
  supabase status --workdir "${V2_RUNTIME_DIR}" -o json 2>/dev/null
}

v2_write_env_files() {
  local status_file
  status_file="$(mktemp)"
  trap 'rm -f "${status_file}"' RETURN
  v2_status_json > "${status_file}"

  node - "${status_file}" "${V2_ROOT_DIR}/.env.local" "${V2_ROOT_DIR}/.env.test.local" <<'NODE'
const fs = require('node:fs')
const [statusPath, ...destinations] = process.argv.slice(2)
const status = JSON.parse(fs.readFileSync(statusPath, 'utf8'))
const required = ['API_URL', 'ANON_KEY', 'SERVICE_ROLE_KEY']
for (const name of required) {
  if (!status[name]) throw new Error(`Supabase status is missing ${name}`)
}
if (status.API_URL !== 'http://127.0.0.1:56321') {
  throw new Error(`Refusing to write env for unexpected API URL: ${status.API_URL}`)
}
const adminLineId = 'U770e3788b27c6cdeb9248b9f7139f171'
const content = [
  '# Generated by scripts/v2-supabase-up for the isolated InkHunt v2 stack.',
  `NEXT_PUBLIC_SUPABASE_URL=${status.API_URL}`,
  `NEXT_PUBLIC_SUPABASE_ANON_KEY=${status.ANON_KEY}`,
  `SUPABASE_SERVICE_ROLE_KEY=${status.SERVICE_ROLE_KEY}`,
  'NEXT_PUBLIC_BASE_URL=http://127.0.0.1:3200',
  `ADMIN_LINE_USER_IDS=${adminLineId}`,
  'INKHUNT_LOCAL_TEST=true',
  'LINE_CHANNEL_ID=local-dev',
  'LINE_CHANNEL_SECRET=local-dev',
  'LINE_MESSAGING_CHANNEL_ACCESS_TOKEN=local-dev',
  '',
].join('\n')
for (const destination of destinations) {
  fs.writeFileSync(destination, content, { mode: 0o600 })
}
NODE
}

v2_require_isolated_stack() {
  local status_file api_url
  status_file="$(mktemp)"
  trap 'rm -f "${status_file}"' RETURN
  v2_status_json > "${status_file}"
  api_url="$(node -e "const fs=require('node:fs'); const s=JSON.parse(fs.readFileSync(process.argv[1], 'utf8')); process.stdout.write(s.API_URL || '')" "${status_file}")"
  if [[ "${api_url}" != "${V2_API_URL}" ]]; then
    echo "Refusing to continue: expected isolated API ${V2_API_URL}, got ${api_url:-none}." >&2
    return 1
  fi
  if ! docker ps --format '{{.Names}}' | grep -q "_${V2_PROJECT_ID}$"; then
    echo "Refusing to continue: no running Docker container belongs to ${V2_PROJECT_ID}." >&2
    return 1
  fi
}
